import java.util.Scanner;

//criando a classe do Main
public class Main{

public static void main(String[] args){

    Scanner sc = new Scanner(System.in);
    boolean menu = true;

//criando o menu
    while (menu){

        System.out.println("\nCalculadora de geometria");
        System.out.println("1 - Cículo");
        System.out.println("2 - Quadrado");
        System.out.println("3 - Cubo");
        System.out.println("4 - Esfera");
        System.out.println("5 - Sair/Fechar");
        System.out.print("Escolha uma das opções acima: \n");

        int option = sc.nextInt();

        switch (option){

            

        }

//

        }

    }

}

}

