import java.util.Scanner;

//criando a classe do Main
public class Main{

public static void main(String[] args){

    Scanner sc = new Scanner(System.in);
    boolean menu = true;

//criando o menu
    while (menu){

        System.out.println("\nCalculadora de geomtria");
        System.out.println("1 - Cículo");
        System.out.println("2 - Quadrado");
        System.out.println("3 - Cubo");
        System.out.println("4 - Esfera");
        System.out.println("5 - Sair/Fechar");
        System.out.print("Escolha uma das opções acima: \n");

        int option = sc.nextInt();

        switch (option){

            case 1:
System.out.println("");
            break;
            case 2:
System.out.println("");
            break;
            case 3:
System.out.println("");
            break;
            case 4:
System.out.println("");
            break;
            case 5:
System.out.println("");
            break;
System.out.println("");
            default:
            System.out.println("");

        }

    }

}

}

